platform :ios, '9.0'
inhibit_all_warnings!

target 'QNRTNiuLiving' do
  pod "PLMediaStreamingKit"
  pod 'BlocksKit', '2.2.5'
  #pod "PLMediaStreamingKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLMediaStreamingKit/master/PLMediaStreamingKit-Universal.podspec'
  #pod "PLPlayerKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'
  pod 'Bugsnag', '5.15.4'
end
