platform :ios, '9.0'
inhibit_all_warnings!

target 'QNRTNiuLiving' do
  pod "QNRTPlayerKit", :path =>'../QNRTPlayerKit.podspec'
  pod "PLMediaStreamingKit"
  pod 'BlocksKit', '2.2.5'
  pod 'Bugsnag', '5.15.4'
end
